import { motion } from 'motion/react';
import { FileText, Download, Share2, Check, Calendar, TrendingDown, Leaf, Factory } from 'lucide-react';

export default function ESGReport() {
  return (
    <div className="min-h-screen bg-[#0B0F14] px-6 py-12">
      {/* Background grid */}
      <div className="fixed inset-0 bg-[linear-gradient(to_right,#121821_1px,transparent_1px),linear-gradient(to_bottom,#121821_1px,transparent_1px)] bg-[size:4rem_4rem] opacity-20 pointer-events-none"></div>

      <div className="relative max-w-6xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12"
        >
          <h1 className="text-5xl font-bold mb-4 bg-gradient-to-r from-white to-[#00C6FF] bg-clip-text text-transparent">
            ESG Report Preview
          </h1>
          <p className="text-gray-400">AI-generated compliance documentation</p>
        </motion.div>

        {/* Action Buttons */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="flex gap-4 mb-8"
        >
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            className="px-6 py-3 bg-gradient-to-r from-[#00C6FF] to-[#00FFB2] text-[#0B0F14] rounded-lg font-medium shadow-lg shadow-[#00C6FF]/30 hover:shadow-xl hover:shadow-[#00C6FF]/50 transition-all flex items-center gap-2"
          >
            <Download className="w-5 h-5" />
            Download PDF
          </motion.button>
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            className="px-6 py-3 bg-[#121821] text-white rounded-lg font-medium border border-[#00C6FF]/30 hover:border-[#00C6FF] transition-all flex items-center gap-2"
          >
            <Share2 className="w-5 h-5" />
            Share Report
          </motion.button>
        </motion.div>

        {/* Report Preview */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="bg-[#121821] border border-[#00C6FF]/20 rounded-xl overflow-hidden shadow-2xl"
        >
          {/* Report Header */}
          <div className="bg-gradient-to-r from-[#121821] to-[#1a2332] border-b border-[#00C6FF]/20 p-8">
            <div className="flex items-start justify-between">
              <div>
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-12 h-12 bg-gradient-to-br from-[#00C6FF] to-[#00FFB2] rounded-lg flex items-center justify-center">
                    <FileText className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <h2 className="text-2xl font-bold text-white">ESG Compliance Report</h2>
                    <p className="text-gray-400">Q1 2026 • Generated by CarbonPilot AI</p>
                  </div>
                </div>
                <div className="flex items-center gap-4 text-sm">
                  <span className="flex items-center gap-2 text-gray-400">
                    <Calendar className="w-4 h-4" />
                    March 3, 2026
                  </span>
                  <span className="px-3 py-1 bg-[#00E676]/20 text-[#00E676] rounded-full border border-[#00E676]/30">
                    CBAM Compliant
                  </span>
                </div>
              </div>
              <div className="text-right">
                <p className="text-sm text-gray-400 mb-1">Report ID</p>
                <p className="text-white font-mono">CPT-2026-Q1-8274</p>
              </div>
            </div>
          </div>

          {/* Report Content */}
          <div className="p-8 space-y-8">
            {/* Emission Summary */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
            >
              <h3 className="text-xl font-semibold text-white mb-6 flex items-center gap-2">
                <div className="w-8 h-8 bg-gradient-to-br from-[#00C6FF] to-[#1E90FF] rounded-lg flex items-center justify-center">
                  <TrendingDown className="w-4 h-4 text-white" />
                </div>
                Emission Summary
              </h3>
              <div className="grid md:grid-cols-3 gap-6">
                {[
                  { label: 'Total Emissions', value: '127.4', unit: 'tCO2e', change: '-11.2%' },
                  { label: 'Carbon Intensity', value: '1.08', unit: 'kgCO2e/unit', change: '-13.6%' },
                  { label: 'Scope 1+2 Combined', value: '104.8', unit: 'tCO2e', change: '-9.8%' }
                ].map((item, index) => (
                  <div key={index} className="bg-[#0B0F14]/50 border border-[#00C6FF]/20 rounded-lg p-5">
                    <p className="text-sm text-gray-400 mb-2">{item.label}</p>
                    <div className="flex items-baseline gap-2 mb-2">
                      <span className="text-3xl font-bold text-white">{item.value}</span>
                      <span className="text-gray-400">{item.unit}</span>
                    </div>
                    <span className="text-[#00E676] text-sm font-semibold">{item.change} vs Q4 2025</span>
                  </div>
                ))}
              </div>
            </motion.section>

            {/* Carbon Breakdown */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
            >
              <h3 className="text-xl font-semibold text-white mb-6 flex items-center gap-2">
                <div className="w-8 h-8 bg-gradient-to-br from-[#00FFB2] to-[#00E676] rounded-lg flex items-center justify-center">
                  <Leaf className="w-4 h-4 text-white" />
                </div>
                Carbon Breakdown (Scope 1, 2)
              </h3>
              <div className="space-y-4">
                {[
                  { scope: 'Scope 1', category: 'Direct Emissions', amount: 45.2, percentage: 35.5, color: 'from-[#00C6FF] to-[#1E90FF]' },
                  { scope: 'Scope 2', category: 'Indirect Emissions (Electricity)', amount: 59.6, percentage: 46.8, color: 'from-[#00FFB2] to-[#00E676]' },
                  { scope: 'Scope 3', category: 'Value Chain Emissions', amount: 22.6, percentage: 17.7, color: 'from-[#FFB020] to-[#00E676]' }
                ].map((item, index) => (
                  <div key={index} className="bg-[#0B0F14]/50 border border-[#00C6FF]/20 rounded-lg p-5">
                    <div className="flex items-center justify-between mb-3">
                      <div>
                        <p className="text-white font-semibold">{item.scope}</p>
                        <p className="text-sm text-gray-400">{item.category}</p>
                      </div>
                      <div className="text-right">
                        <p className="text-2xl font-bold text-white">{item.amount}</p>
                        <p className="text-sm text-gray-400">tCO2e</p>
                      </div>
                    </div>
                    <div className="relative h-2 bg-[#1a2332] rounded-full overflow-hidden">
                      <motion.div
                        className={`h-full bg-gradient-to-r ${item.color} rounded-full`}
                        initial={{ width: 0 }}
                        animate={{ width: `${item.percentage}%` }}
                        transition={{ delay: 0.5 + index * 0.1, duration: 1 }}
                      />
                    </div>
                    <p className="text-sm text-gray-400 mt-2">{item.percentage}% of total emissions</p>
                  </div>
                ))}
              </div>
            </motion.section>

            {/* 90-Day Reduction Roadmap */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 }}
            >
              <h3 className="text-xl font-semibold text-white mb-6 flex items-center gap-2">
                <div className="w-8 h-8 bg-gradient-to-br from-[#1E90FF] to-[#00C6FF] rounded-lg flex items-center justify-center">
                  <Calendar className="w-4 h-4 text-white" />
                </div>
                90-Day Reduction Roadmap
              </h3>
              <div className="space-y-4">
                {[
                  { phase: 'Month 1', action: 'Install IoT sensors and baseline measurement', target: '2% reduction', status: 'completed' },
                  { phase: 'Month 2', action: 'Implement production scheduling optimization', target: '5% reduction', status: 'completed' },
                  { phase: 'Month 3', action: 'Equipment efficiency upgrades and ML tuning', target: '4% reduction', status: 'in-progress' }
                ].map((item, index) => (
                  <div key={index} className="bg-[#0B0F14]/50 border border-[#00C6FF]/20 rounded-lg p-5 hover:border-[#00C6FF]/50 transition-all">
                    <div className="flex items-start gap-4">
                      <div className={`w-10 h-10 rounded-full flex items-center justify-center ${
                        item.status === 'completed' ? 'bg-[#00E676]/20 border-2 border-[#00E676]' : 'bg-[#1E90FF]/20 border-2 border-[#1E90FF]'
                      }`}>
                        {item.status === 'completed' ? (
                          <Check className="w-5 h-5 text-[#00E676]" />
                        ) : (
                          <span className="text-[#1E90FF] font-semibold">{index + 1}</span>
                        )}
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center justify-between mb-2">
                          <p className="text-white font-semibold">{item.phase}</p>
                          <span className={`px-3 py-1 text-xs rounded-full ${
                            item.status === 'completed' 
                              ? 'bg-[#00E676]/20 text-[#00E676] border border-[#00E676]/30'
                              : 'bg-[#1E90FF]/20 text-[#1E90FF] border border-[#1E90FF]/30'
                          }`}>
                            {item.status === 'completed' ? 'Completed' : 'In Progress'}
                          </span>
                        </div>
                        <p className="text-gray-400 mb-2">{item.action}</p>
                        <p className="text-[#00FFB2] text-sm font-semibold">Target: {item.target}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </motion.section>

            {/* CBAM Compliance Overview */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.6 }}
            >
              <h3 className="text-xl font-semibold text-white mb-6 flex items-center gap-2">
                <div className="w-8 h-8 bg-gradient-to-br from-[#00E676] to-[#00FFB2] rounded-lg flex items-center justify-center">
                  <Factory className="w-4 h-4 text-white" />
                </div>
                CBAM Compliance Overview
              </h3>
              <div className="bg-[#0B0F14]/50 border border-[#00E676]/30 rounded-lg p-6">
                <div className="grid md:grid-cols-2 gap-6">
                  <div>
                    <p className="text-sm text-gray-400 mb-3">Compliance Status</p>
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-12 h-12 bg-[#00E676]/20 rounded-full flex items-center justify-center border-2 border-[#00E676]">
                        <Check className="w-6 h-6 text-[#00E676]" />
                      </div>
                      <div>
                        <p className="text-xl font-bold text-[#00E676]">Fully Compliant</p>
                        <p className="text-sm text-gray-400">EU CBAM Requirements Met</p>
                      </div>
                    </div>
                  </div>
                  <div>
                    <p className="text-sm text-gray-400 mb-3">Documentation</p>
                    <div className="space-y-2">
                      {['Emission boundaries defined', 'Calculation methods verified', 'Third-party verification ready'].map((item, index) => (
                        <div key={index} className="flex items-center gap-2">
                          <Check className="w-4 h-4 text-[#00E676]" />
                          <span className="text-gray-300 text-sm">{item}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </motion.section>

            {/* AI Insight Commentary */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.7 }}
              className="bg-gradient-to-br from-[#121821] to-[#1a2332] border border-[#00C6FF]/30 rounded-lg p-6"
            >
              <h3 className="text-xl font-semibold text-white mb-4">AI Insight Commentary</h3>
              <div className="space-y-4 text-gray-300 leading-relaxed">
                <p>
                  Based on comprehensive data analysis, this facility has demonstrated exceptional progress in carbon reduction initiatives. 
                  The 13.6% decrease in carbon intensity over Q1 2026 significantly outperforms industry benchmarks.
                </p>
                <p>
                  Machine learning models predict continued improvement trajectory with current optimization strategies. 
                  Key drivers include production scheduling efficiency (+22% contribution), equipment optimization (+31% contribution), 
                  and process refinement (+47% contribution).
                </p>
                <p className="text-[#00FFB2] font-semibold">
                  Recommendation: Maintain current optimization protocols while exploring heat recovery systems for additional 8.5% efficiency gains.
                </p>
              </div>
            </motion.section>
          </div>

          {/* Report Footer */}
          <div className="bg-[#0B0F14]/50 border-t border-[#00C6FF]/20 p-6 text-center text-sm text-gray-400">
            <p>Generated by CarbonPilot AI • Data-Driven Decarbonization for the New Industrial Era</p>
            <p className="mt-2">Report certified accurate to ISO 14064-1 standards</p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
